# Generated by Django 5.0.7 on 2024-11-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=50)),
                ("vintage_year", models.PositiveIntegerField()),
                ("region", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("rating", models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
