# Generated by Django 5.0.7 on 2024-11-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wines", "0002_wine_alcohol_wine_bottle_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wine",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="wine",
            name="Alcohol",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="wine",
            name="Bottle_size",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="wine",
            name="serving_temperature",
            field=models.CharField(default="", max_length=50),
        ),
    ]
