# Generated by Django 5.0.7 on 2024-11-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wines", "0003_wine_image_alter_wine_alcohol_alter_wine_bottle_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wine",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
